#!/bin/bash
set -euxo pipefail

DB=$(mktemp)

# Insert the 3 sheets from the Excel file with some form of primary key
sqlite-utils insert --csv $DB FurtherExplanation FurtherExplanation.csv --pk 'Legal Basis for Provision of Data (Dissemination)'
for Y in 2019 2020 2021; do
    for M in 01 02 03 04 05 06 07 08 09 10 11 12; do
        if [ -d "$Y-$M" ]; then sqlite-utils insert --csv $DB PurposeStatements $Y-$M/PurposeStatements.csv --pk 'Reference Number' --replace; fi
        if [ -d "$Y-$M" ]; then sqlite-utils insert --csv $DB DataReleases $Y-$M/DataReleases.csv --pk ID --replace; fi
        if [ -f "$Y-$M/Amendments.csv" ]; then sqlite-utils insert --csv $DB DataReleases $Y-$M/Amendments.csv --pk ID --replace; fi
    done
done

# Extract the organisations to their own table
sqlite-utils extract $DB DataReleases 'Organisation Name' --table Organisations --rename 'Organisation Name' 'name'
sqlite-utils extract $DB PurposeStatements 'Organisation' --table Organisations --rename 'Organisation' 'name'

# Turn on some full text search
sqlite-utils enable-fts $DB PurposeStatements 'Objective for Processing' 'Processing Activities' 'Expected Output' 'Expected Measurable Benefits' 'Yielded Benefits'
sqlite-utils enable-fts $DB Organisations 'name'

# Add some foreign keys
sqlite-utils add-foreign-key $DB DataReleases 'NIC Number' PurposeStatements 'Reference Number'
sqlite-utils add-foreign-key $DB DataReleases 'Legal Basis for Provision of Data (Dissemination)' FurtherExplanation 'Legal Basis for Provision of Data (Dissemination)'

# Done
mv $DB nhs-data-release-register.db
